# Site settings
title: Maharbiz Group Cyborg Insects
email: mann@berkeley.edu
description: "Maharbiz Group Insect Control Project"
baseurl: "http://maharbizgroup.github.io/insect-control/"
url: "http://maharbizgroup.github.io/insect-control/"
twitter_username: 
github_username:  maharbizgroup

# Build settings
markdown: kramdown
permalink: pretty
